version: "3.9" 

services:
  mongo:
    container_name: mongo 
    build:
      dockerfile: docker/mongo-replica-set.Dockerfile
      context: .
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: developmentuser
      MINIO_ROOT_PASSWORD: developmentpassword
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_ADDRESS: ":9001"
    restart: always
    ports:
      - "9000:9000"
      - "3003:9001"
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  mongo_data: ~
  minio_data: ~

