name: '🔧 Setup Environment'
description: 'Does things necessary for most workflows.'

runs:
  using: "composite"
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install Dependencies
      shell: bash
      run: yarn install
