name: '🔧 Setup Environment'
description: 'Does things necessary for most workflows.'

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Yarn
      uses: threeal/setup-yarn-action@v1.0.0

    - name: Install Dependencies
      shell: bash
      run: yarn install
